#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *

SERVICE_NAME = "RouteService"
SERVICE_VERSION = "1.0"
ROUTE_STATE_INTERIOR = 1
ROUTE_FLAG_ADD_OVERWRITE = 1
